services:

  postgres:
    image: postgres:17
    container_name: banking-postgres

    environment:
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
      POSTGRES_DB: banking

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking -d banking"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: banking-api/Dockerfile

    container_name: api-gateway

    environment:
      APP_NAME: banking-api
      APP_PORT: "8080"

      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: banking
      DB_PASSWORD: banking
      DB_NAME: banking
      DB_SSLMODE: disable

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: