services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
      POSTGRES_DB: banking

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking -d banking"]
      interval: 10s
      timeout: 5s
      retries: 5

  banking-api:
    build:
      context: .
      dockerfile: banking-api/Dockerfile

    environment:
      APP_NAME: banking-api
      APP_PORT: "8080"

      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: banking
      DB_PASSWORD: banking
      DB_NAME: banking
      DB_SSLMODE: disable

      # Aktifkan nanti jika ingin memakai OTLP
      # OTEL_SERVICE_NAME: banking-api
      # OTEL_EXPORTER_OTLP_ENDPOINT: ${DT_OTLP_ENDPOINT}
      # OTEL_EXPORTER_OTLP_HEADERS: Authorization=Api-Token ${DT_API_TOKEN}
      # OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong:
    image: kong:3.9

    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      DT_NGINX_FORCE_RUNTIME_INSTRUMENTATION: "on"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr

    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro

    ports:
      - "8000:8000"
      - "8001:8001"

    depends_on:
      banking-api:
        condition: service_healthy

  # load-generator:
  #   build:
  #     context: ./load-generator
  #     dockerfile: Dockerfile

  #   container_name: load-generator

  #   env_file:
  #     - ./load-generator/.env

  #   depends_on:
  #     banking-api:
  #       condition: service_healthy

volumes:
  postgres-data:
